// Generated by LiveScript 1.3.1
var start, isBlink, isLight, isRun, isShow, isWarned, handler, latency, stopBy, delay, audioRemind, audioEnd, rippleCanvas, rippleCtx, rippleRadius, rippleSpeed, rippleMax, rippleReq, timerEl, fbtns, newAudio, soundToggle, show, adjust, toggle, reset, blink, count, run, resize, drawRipple, startRipple, stopRipple, bindButtons;
start = null;
isBlink = false;
isLight = true;
isRun = false;
isShow = true;
isWarned = false;
handler = null;
latency = 0;
stopBy = null;
delay = 60000;
audioRemind = null;
audioEnd = null;
rippleCanvas = null;
rippleCtx = null;
rippleRadius = 0;
rippleSpeed = 2;
rippleMax = 0;
rippleReq = null;
newAudio = function(file){
  var x$, node;
  x$ = node = new Audio();
  x$.src = file;
  x$.loop = false;
  x$.load();
  document.body.appendChild(node);
  return node;
};
soundToggle = function(des, state){
  var x$;
  if (state) {
    return des.play();
  } else {
    x$ = des;
    x$.currentTime = 0;
    x$.pause();
    return x$;
  }
};
show = function(){
  isShow = !isShow;
  if (fbtns) {
    return fbtns.forEach(function(btn){
      return btn.style.opacity = isShow ? '1.0' : '0.1';
    });
  }
};
adjust = function(it, v){
  if (isBlink) {
    return;
  }
  delay = delay + it * 1000;
  if (it === 0) {
    delay = v * 1000;
  }
  if (delay <= 0) {
    delay = 0;
  }
  if (timerEl) {
    timerEl.textContent = delay;
  }
  return resize();
};
toggle = function(){
  isRun = !isRun;
  document.getElementById('toggle').textContent = isRun ? "STOP" : "RUN";
  if (!isRun && handler) {
    stopBy = new Date();
    clearInterval(handler);
    handler = null;
    soundToggle(audioEnd, false);
    soundToggle(audioRemind, false);
    stopRipple();
  }
  if (stopBy) {
    latency = latency + new Date().getTime() - stopBy.getTime();
  }
  if (isRun) {
    return run();
  }
};
reset = function(){
  if (delay === 0) {
    delay = 1000;
  }
  soundToggle(audioRemind, false);
  soundToggle(audioEnd, false);
  stopBy = 0;
  isWarned = false;
  isBlink = false;
  latency = 0;
  start = null;
  isRun = true;
  toggle();
  if (handler) {
    clearInterval(handler);
  }
  handler = null;
  if (timerEl) {
    timerEl.textContent = delay;
    timerEl.style.color = '#fff';
  }
  stopRipple();
  return resize();
};
blink = function(){
  isBlink = true;
  isLight = !isLight;
  if (timerEl) {
    return timerEl.style.color = isLight ? '#fff' : '#f00';
  }
};
count = function(){
  var tm, diff;
  tm = timerEl;
  diff = start.getTime() - new Date().getTime() + delay + latency;
  if (diff > 60000) {
    isWarned = false;
  }
  if (diff < 60000 && !isWarned) {
    isWarned = true;
    soundToggle(audioRemind, true);
  }
  if (diff < 55000) {
    soundToggle(audioRemind, false);
  }
  if (diff < 0 && !isBlink) {
    soundToggle(audioEnd, true);
    isBlink = true;
    diff = 0;
    clearInterval(handler);
    stopRipple();
    handler = setInterval(function(){
      return blink();
    }, 500);
  }
  if (tm) {
    tm.textContent = diff + "";
  }
  return resize();
};
run = function(){
  if (start === null) {
    start = new Date();
    latency = 0;
    isBlink = false;
  }
  if (handler) {
    clearInterval(handler);
  }
  if (isBlink) {
    stopRipple();
    return handler = setInterval(function(){
      return blink();
    }, 500);
  } else {
    startRipple();
    return handler = setInterval(function(){
      return count();
    }, 100);
  }
};
resize = function(){
  var tm, w, h, len;
  tm = timerEl;
  w = tm ? tm.getBoundingClientRect().width : window.innerWidth;
  h = window.innerHeight;
  len = tm && tm.textContent ? tm.textContent.length : 3;
  len >= 3 || (len = 3);
  if (tm) {
    tm.style.fontSize = 1.5 * w / len + "px";
    tm.style.lineHeight = h + "px";
  }
  if (rippleCanvas) {
    rippleCanvas.width = w;
    rippleCanvas.height = h;
    rippleMax = Math.min(w, h) / 2;
  }
};
drawRipple = function(){
  if (!rippleCtx || !rippleCanvas) {
    return;
  }
  rippleCtx.clearRect(0, 0, rippleCanvas.width, rippleCanvas.height);
  rippleCtx.beginPath();
  rippleCtx.arc(rippleCanvas.width / 2, rippleCanvas.height / 2, rippleRadius, 0, Math.PI * 2, false);
  rippleCtx.strokeStyle = 'rgba(255,255,255,0.6)';
  rippleCtx.lineWidth = 4;
  rippleCtx.stroke();
  rippleRadius += rippleSpeed;
  if (rippleRadius >= rippleMax) {
    rippleRadius = rippleMax;
    rippleSpeed = -Math.abs(rippleSpeed);
  }
  if (rippleRadius <= 0) {
    rippleRadius = 0;
    rippleSpeed = Math.abs(rippleSpeed);
  }
  return rippleReq = requestAnimationFrame(function(){
    return drawRipple();
  });
};
startRipple = function(){
  var ref$;
  if (!rippleCanvas) {
    rippleCanvas = document.getElementById('ripple');
  }
  if (!rippleCanvas) {
    return;
  }
  rippleCtx = (ref$ = rippleCtx) != null ? ref$ : rippleCanvas.getContext('2d');
  resize();
  if (rippleReq) {
    return;
  }
  rippleRadius = 0;
  rippleSpeed = Math.abs(rippleSpeed) || 2;
  return drawRipple();
};
stopRipple = function(){
  if (rippleReq) {
    cancelAnimationFrame(rippleReq);
    rippleReq = null;
  }
  if (rippleCtx && rippleCanvas) {
    return rippleCtx.clearRect(0, 0, rippleCanvas.width, rippleCanvas.height);
  }
};
bindButtons = function(){
  var adjustButtons, setButtons, toggleBtn, resetBtn, hideBtn;
  adjustButtons = Array.prototype.slice.call(document.querySelectorAll('[data-adjust]'));
  setButtons = Array.prototype.slice.call(document.querySelectorAll('[data-set]'));
  toggleBtn = document.getElementById('toggle');
  resetBtn = document.getElementById('reset');
  hideBtn = document.getElementById('hide');
  adjustButtons.forEach(function(btn){
    return btn.addEventListener('click', function(e){
      e.preventDefault();
      return adjust(parseInt(btn.getAttribute('data-adjust'), 10));
    });
  });
  setButtons.forEach(function(btn){
    return btn.addEventListener('click', function(e){
      e.preventDefault();
      return adjust(0, parseInt(btn.getAttribute('data-set'), 10));
    });
  });
  if (toggleBtn) {
    toggleBtn.addEventListener('click', function(e){
      e.preventDefault();
      return toggle();
    });
  }
  if (resetBtn) {
    resetBtn.addEventListener('click', function(e){
      e.preventDefault();
      return reset();
    });
  }
  if (hideBtn) {
    return hideBtn.addEventListener('click', function(e){
      e.preventDefault();
      return show();
    });
  }
};
window.onload = function(){
  timerEl = document.getElementById('timer');
  fbtns = Array.prototype.slice.call(document.querySelectorAll('.fbtn'));
  if (timerEl) {
    timerEl.textContent = delay;
  }
  bindButtons();
  rippleCanvas = document.getElementById('ripple');
  if (rippleCanvas) {
    rippleCtx = rippleCanvas.getContext('2d');
  }
  resize();
  audioRemind = newAudio('audio/smb_warning.mp3');
  return audioEnd = newAudio('audio/smb_mariodie.mp3');
};
window.onresize = function(){
  return resize();
};
